version: "2"
services:
  app:
    container_name: app
    restart: always
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
      - "80:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
